language: python

python:
    - "2.6"
    - "2.7"
    - "3.2"
    - "3.3"
    - "3.4"

env:
    - DJANGO=1.4.16
    - DJANGO=1.5.11
    - DJANGO=1.6.8
    - DJANGO=1.7.1

matrix:
    exclude:
        - python: "2.6"
          env: DJANGO=1.7.1
        - python: "3.2"
          env: DJANGO=1.4.16
        - python: "3.3"
          env: DJANGO=1.4.16
        - python: "3.4"
          env: DJANGO=1.4.16

before_install:
    - sudo apt-get install libgeoip-dev

install:
    - pip install -q Django==$DJANGO
    - pip install geoip
    - pip install coverage django-discover-runner mock unittest2
    - python setup.py develop

script:
    - python example/manage.py test --verbosity=2
