language: python
python:
    - "2.6"
    - "2.7"
    - "3.2"
    - "3.3"
    - "3.4"

env:
    - DJANGO=1.4.13
    - DJANGO=1.5.8
    - DJANGO=1.6.5
virtualenv:
    system_site_packages: true
install:
    - pip install -q Django==$DJANGO --use-mirrors
script:
    - python setup.py test
