language: python

python:
    - "2.6"
    - "2.7"
    - "3.2"
    - "3.3"
    - "3.4"

env:
    - DJANGO=1.4.13
    - DJANGO=1.5.8
    - DJANGO=1.6.5
    - DJANGO=1.7.1

matrix:
    exclude:
        - python: "2.6"
          env: DJANGO=1.7.1
        - python: "3.2"
          env: DJANGO=1.4.13
        - python: "3.3"
          env: DJANGO=1.4.13
        - python: "3.4"
          env: DJANGO=1.4.13

before_install:
    - sudo apt-get install libgeoip-dev

install:
    - pip install -q Django==$DJANGO --use-mirrors
    - pip install geoip --use-mirrors
    - pip install mock coverage unittest2 --use-mirrors
    - python setup.py develop

script:
    - python example/manage.py test
